package protocol.network.types.game.character.characteristic;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import protocol.utils.ProtocolTypeManager;
import protocol.network.util.types.BooleanByteWrapper;

import protocol.network.NetworkMessage;
import protocol.network.util.DofusDataReader;
import protocol.network.util.DofusDataWriter;
import protocol.network.Network;
import protocol.network.NetworkMessage;
import protocol.network.types.game.character.alignment.ActorExtendedAlignmentInformations;
import protocol.network.types.game.character.characteristic.CharacterBaseCharacteristic;
import protocol.network.types.game.character.characteristic.CharacterSpellModification;

@SuppressWarnings("unused")
public class CharacterCharacteristicsInformations extends NetworkMessage {
	public static final int ProtocolId = 8;

	public long experience;
	public long experienceLevelFloor;
	public long experienceNextLevelFloor;
	public long experienceBonusLimit;
	public long kamas;
	public int statsPoints;
	public int additionnalPoints;
	public int spellsPoints;
	public ActorExtendedAlignmentInformations alignmentInfos;
	public int lifePoints;
	public int maxLifePoints;
	public int energyPoints;
	public int maxEnergyPoints;
	public int actionPointsCurrent;
	public int movementPointsCurrent;
	public CharacterBaseCharacteristic initiative;
	public CharacterBaseCharacteristic prospecting;
	public CharacterBaseCharacteristic actionPoints;
	public CharacterBaseCharacteristic movementPoints;
	public CharacterBaseCharacteristic strength;
	public CharacterBaseCharacteristic vitality;
	public CharacterBaseCharacteristic wisdom;
	public CharacterBaseCharacteristic chance;
	public CharacterBaseCharacteristic agility;
	public CharacterBaseCharacteristic intelligence;
	public CharacterBaseCharacteristic range;
	public CharacterBaseCharacteristic summonableCreaturesBoost;
	public CharacterBaseCharacteristic reflect;
	public CharacterBaseCharacteristic criticalHit;
	public int criticalHitWeapon;
	public CharacterBaseCharacteristic criticalMiss;
	public CharacterBaseCharacteristic healBonus;
	public CharacterBaseCharacteristic allDamagesBonus;
	public CharacterBaseCharacteristic weaponDamagesBonusPercent;
	public CharacterBaseCharacteristic damagesBonusPercent;
	public CharacterBaseCharacteristic trapBonus;
	public CharacterBaseCharacteristic trapBonusPercent;
	public CharacterBaseCharacteristic glyphBonusPercent;
	public CharacterBaseCharacteristic runeBonusPercent;
	public CharacterBaseCharacteristic permanentDamagePercent;
	public CharacterBaseCharacteristic tackleBlock;
	public CharacterBaseCharacteristic tackleEvade;
	public CharacterBaseCharacteristic PAAttack;
	public CharacterBaseCharacteristic PMAttack;
	public CharacterBaseCharacteristic pushDamageBonus;
	public CharacterBaseCharacteristic criticalDamageBonus;
	public CharacterBaseCharacteristic neutralDamageBonus;
	public CharacterBaseCharacteristic earthDamageBonus;
	public CharacterBaseCharacteristic waterDamageBonus;
	public CharacterBaseCharacteristic airDamageBonus;
	public CharacterBaseCharacteristic fireDamageBonus;
	public CharacterBaseCharacteristic dodgePALostProbability;
	public CharacterBaseCharacteristic dodgePMLostProbability;
	public CharacterBaseCharacteristic neutralElementResistPercent;
	public CharacterBaseCharacteristic earthElementResistPercent;
	public CharacterBaseCharacteristic waterElementResistPercent;
	public CharacterBaseCharacteristic airElementResistPercent;
	public CharacterBaseCharacteristic fireElementResistPercent;
	public CharacterBaseCharacteristic neutralElementReduction;
	public CharacterBaseCharacteristic earthElementReduction;
	public CharacterBaseCharacteristic waterElementReduction;
	public CharacterBaseCharacteristic airElementReduction;
	public CharacterBaseCharacteristic fireElementReduction;
	public CharacterBaseCharacteristic pushDamageReduction;
	public CharacterBaseCharacteristic criticalDamageReduction;
	public CharacterBaseCharacteristic pvpNeutralElementResistPercent;
	public CharacterBaseCharacteristic pvpEarthElementResistPercent;
	public CharacterBaseCharacteristic pvpWaterElementResistPercent;
	public CharacterBaseCharacteristic pvpAirElementResistPercent;
	public CharacterBaseCharacteristic pvpFireElementResistPercent;
	public CharacterBaseCharacteristic pvpNeutralElementReduction;
	public CharacterBaseCharacteristic pvpEarthElementReduction;
	public CharacterBaseCharacteristic pvpWaterElementReduction;
	public CharacterBaseCharacteristic pvpAirElementReduction;
	public CharacterBaseCharacteristic pvpFireElementReduction;
	public CharacterBaseCharacteristic meleeDamageDonePercent;
	public CharacterBaseCharacteristic meleeDamageReceivedPercent;
	public CharacterBaseCharacteristic rangedDamageDonePercent;
	public CharacterBaseCharacteristic rangedDamageReceivedPercent;
	public CharacterBaseCharacteristic weaponDamageDonePercent;
	public CharacterBaseCharacteristic weaponDamageReceivedPercent;
	public CharacterBaseCharacteristic spellDamageDonePercent;
	public CharacterBaseCharacteristic spellDamageReceivedPercent;
	public List<CharacterSpellModification> spellModifications;
	public int probationTime;

	public CharacterCharacteristicsInformations(){
	}

	public CharacterCharacteristicsInformations(long experience, long experienceLevelFloor, long experienceNextLevelFloor, long experienceBonusLimit, long kamas, int statsPoints, int additionnalPoints, int spellsPoints, ActorExtendedAlignmentInformations alignmentInfos, int lifePoints, int maxLifePoints, int energyPoints, int maxEnergyPoints, int actionPointsCurrent, int movementPointsCurrent, CharacterBaseCharacteristic initiative, CharacterBaseCharacteristic prospecting, CharacterBaseCharacteristic actionPoints, CharacterBaseCharacteristic movementPoints, CharacterBaseCharacteristic strength, CharacterBaseCharacteristic vitality, CharacterBaseCharacteristic wisdom, CharacterBaseCharacteristic chance, CharacterBaseCharacteristic agility, CharacterBaseCharacteristic intelligence, CharacterBaseCharacteristic range, CharacterBaseCharacteristic summonableCreaturesBoost, CharacterBaseCharacteristic reflect, CharacterBaseCharacteristic criticalHit, int criticalHitWeapon, CharacterBaseCharacteristic criticalMiss, CharacterBaseCharacteristic healBonus, CharacterBaseCharacteristic allDamagesBonus, CharacterBaseCharacteristic weaponDamagesBonusPercent, CharacterBaseCharacteristic damagesBonusPercent, CharacterBaseCharacteristic trapBonus, CharacterBaseCharacteristic trapBonusPercent, CharacterBaseCharacteristic glyphBonusPercent, CharacterBaseCharacteristic runeBonusPercent, CharacterBaseCharacteristic permanentDamagePercent, CharacterBaseCharacteristic tackleBlock, CharacterBaseCharacteristic tackleEvade, CharacterBaseCharacteristic PAAttack, CharacterBaseCharacteristic PMAttack, CharacterBaseCharacteristic pushDamageBonus, CharacterBaseCharacteristic criticalDamageBonus, CharacterBaseCharacteristic neutralDamageBonus, CharacterBaseCharacteristic earthDamageBonus, CharacterBaseCharacteristic waterDamageBonus, CharacterBaseCharacteristic airDamageBonus, CharacterBaseCharacteristic fireDamageBonus, CharacterBaseCharacteristic dodgePALostProbability, CharacterBaseCharacteristic dodgePMLostProbability, CharacterBaseCharacteristic neutralElementResistPercent, CharacterBaseCharacteristic earthElementResistPercent, CharacterBaseCharacteristic waterElementResistPercent, CharacterBaseCharacteristic airElementResistPercent, CharacterBaseCharacteristic fireElementResistPercent, CharacterBaseCharacteristic neutralElementReduction, CharacterBaseCharacteristic earthElementReduction, CharacterBaseCharacteristic waterElementReduction, CharacterBaseCharacteristic airElementReduction, CharacterBaseCharacteristic fireElementReduction, CharacterBaseCharacteristic pushDamageReduction, CharacterBaseCharacteristic criticalDamageReduction, CharacterBaseCharacteristic pvpNeutralElementResistPercent, CharacterBaseCharacteristic pvpEarthElementResistPercent, CharacterBaseCharacteristic pvpWaterElementResistPercent, CharacterBaseCharacteristic pvpAirElementResistPercent, CharacterBaseCharacteristic pvpFireElementResistPercent, CharacterBaseCharacteristic pvpNeutralElementReduction, CharacterBaseCharacteristic pvpEarthElementReduction, CharacterBaseCharacteristic pvpWaterElementReduction, CharacterBaseCharacteristic pvpAirElementReduction, CharacterBaseCharacteristic pvpFireElementReduction, CharacterBaseCharacteristic meleeDamageDonePercent, CharacterBaseCharacteristic meleeDamageReceivedPercent, CharacterBaseCharacteristic rangedDamageDonePercent, CharacterBaseCharacteristic rangedDamageReceivedPercent, CharacterBaseCharacteristic weaponDamageDonePercent, CharacterBaseCharacteristic weaponDamageReceivedPercent, CharacterBaseCharacteristic spellDamageDonePercent, CharacterBaseCharacteristic spellDamageReceivedPercent, List<CharacterSpellModification> spellModifications, int probationTime){
		this.experience = experience;
		this.experienceLevelFloor = experienceLevelFloor;
		this.experienceNextLevelFloor = experienceNextLevelFloor;
		this.experienceBonusLimit = experienceBonusLimit;
		this.kamas = kamas;
		this.statsPoints = statsPoints;
		this.additionnalPoints = additionnalPoints;
		this.spellsPoints = spellsPoints;
		this.alignmentInfos = alignmentInfos;
		this.lifePoints = lifePoints;
		this.maxLifePoints = maxLifePoints;
		this.energyPoints = energyPoints;
		this.maxEnergyPoints = maxEnergyPoints;
		this.actionPointsCurrent = actionPointsCurrent;
		this.movementPointsCurrent = movementPointsCurrent;
		this.initiative = initiative;
		this.prospecting = prospecting;
		this.actionPoints = actionPoints;
		this.movementPoints = movementPoints;
		this.strength = strength;
		this.vitality = vitality;
		this.wisdom = wisdom;
		this.chance = chance;
		this.agility = agility;
		this.intelligence = intelligence;
		this.range = range;
		this.summonableCreaturesBoost = summonableCreaturesBoost;
		this.reflect = reflect;
		this.criticalHit = criticalHit;
		this.criticalHitWeapon = criticalHitWeapon;
		this.criticalMiss = criticalMiss;
		this.healBonus = healBonus;
		this.allDamagesBonus = allDamagesBonus;
		this.weaponDamagesBonusPercent = weaponDamagesBonusPercent;
		this.damagesBonusPercent = damagesBonusPercent;
		this.trapBonus = trapBonus;
		this.trapBonusPercent = trapBonusPercent;
		this.glyphBonusPercent = glyphBonusPercent;
		this.runeBonusPercent = runeBonusPercent;
		this.permanentDamagePercent = permanentDamagePercent;
		this.tackleBlock = tackleBlock;
		this.tackleEvade = tackleEvade;
		this.PAAttack = PAAttack;
		this.PMAttack = PMAttack;
		this.pushDamageBonus = pushDamageBonus;
		this.criticalDamageBonus = criticalDamageBonus;
		this.neutralDamageBonus = neutralDamageBonus;
		this.earthDamageBonus = earthDamageBonus;
		this.waterDamageBonus = waterDamageBonus;
		this.airDamageBonus = airDamageBonus;
		this.fireDamageBonus = fireDamageBonus;
		this.dodgePALostProbability = dodgePALostProbability;
		this.dodgePMLostProbability = dodgePMLostProbability;
		this.neutralElementResistPercent = neutralElementResistPercent;
		this.earthElementResistPercent = earthElementResistPercent;
		this.waterElementResistPercent = waterElementResistPercent;
		this.airElementResistPercent = airElementResistPercent;
		this.fireElementResistPercent = fireElementResistPercent;
		this.neutralElementReduction = neutralElementReduction;
		this.earthElementReduction = earthElementReduction;
		this.waterElementReduction = waterElementReduction;
		this.airElementReduction = airElementReduction;
		this.fireElementReduction = fireElementReduction;
		this.pushDamageReduction = pushDamageReduction;
		this.criticalDamageReduction = criticalDamageReduction;
		this.pvpNeutralElementResistPercent = pvpNeutralElementResistPercent;
		this.pvpEarthElementResistPercent = pvpEarthElementResistPercent;
		this.pvpWaterElementResistPercent = pvpWaterElementResistPercent;
		this.pvpAirElementResistPercent = pvpAirElementResistPercent;
		this.pvpFireElementResistPercent = pvpFireElementResistPercent;
		this.pvpNeutralElementReduction = pvpNeutralElementReduction;
		this.pvpEarthElementReduction = pvpEarthElementReduction;
		this.pvpWaterElementReduction = pvpWaterElementReduction;
		this.pvpAirElementReduction = pvpAirElementReduction;
		this.pvpFireElementReduction = pvpFireElementReduction;
		this.meleeDamageDonePercent = meleeDamageDonePercent;
		this.meleeDamageReceivedPercent = meleeDamageReceivedPercent;
		this.rangedDamageDonePercent = rangedDamageDonePercent;
		this.rangedDamageReceivedPercent = rangedDamageReceivedPercent;
		this.weaponDamageDonePercent = weaponDamageDonePercent;
		this.weaponDamageReceivedPercent = weaponDamageReceivedPercent;
		this.spellDamageDonePercent = spellDamageDonePercent;
		this.spellDamageReceivedPercent = spellDamageReceivedPercent;
		this.spellModifications = spellModifications;
		this.probationTime = probationTime;
	}

	@Override
	public void Serialize(DofusDataWriter writer) {
		try {
			writer.writeVarLong(this.experience);
			writer.writeVarLong(this.experienceLevelFloor);
			writer.writeVarLong(this.experienceNextLevelFloor);
			writer.writeVarLong(this.experienceBonusLimit);
			writer.writeVarLong(this.kamas);
			writer.writeVarShort(this.statsPoints);
			writer.writeVarShort(this.additionnalPoints);
			writer.writeVarShort(this.spellsPoints);
			alignmentInfos.Serialize(writer);
			writer.writeVarInt(this.lifePoints);
			writer.writeVarInt(this.maxLifePoints);
			writer.writeVarShort(this.energyPoints);
			writer.writeVarShort(this.maxEnergyPoints);
			writer.writeVarShort(this.actionPointsCurrent);
			writer.writeVarShort(this.movementPointsCurrent);
			initiative.Serialize(writer);
			prospecting.Serialize(writer);
			actionPoints.Serialize(writer);
			movementPoints.Serialize(writer);
			strength.Serialize(writer);
			vitality.Serialize(writer);
			wisdom.Serialize(writer);
			chance.Serialize(writer);
			agility.Serialize(writer);
			intelligence.Serialize(writer);
			range.Serialize(writer);
			summonableCreaturesBoost.Serialize(writer);
			reflect.Serialize(writer);
			criticalHit.Serialize(writer);
			writer.writeVarShort(this.criticalHitWeapon);
			criticalMiss.Serialize(writer);
			healBonus.Serialize(writer);
			allDamagesBonus.Serialize(writer);
			weaponDamagesBonusPercent.Serialize(writer);
			damagesBonusPercent.Serialize(writer);
			trapBonus.Serialize(writer);
			trapBonusPercent.Serialize(writer);
			glyphBonusPercent.Serialize(writer);
			runeBonusPercent.Serialize(writer);
			permanentDamagePercent.Serialize(writer);
			tackleBlock.Serialize(writer);
			tackleEvade.Serialize(writer);
			PAAttack.Serialize(writer);
			PMAttack.Serialize(writer);
			pushDamageBonus.Serialize(writer);
			criticalDamageBonus.Serialize(writer);
			neutralDamageBonus.Serialize(writer);
			earthDamageBonus.Serialize(writer);
			waterDamageBonus.Serialize(writer);
			airDamageBonus.Serialize(writer);
			fireDamageBonus.Serialize(writer);
			dodgePALostProbability.Serialize(writer);
			dodgePMLostProbability.Serialize(writer);
			neutralElementResistPercent.Serialize(writer);
			earthElementResistPercent.Serialize(writer);
			waterElementResistPercent.Serialize(writer);
			airElementResistPercent.Serialize(writer);
			fireElementResistPercent.Serialize(writer);
			neutralElementReduction.Serialize(writer);
			earthElementReduction.Serialize(writer);
			waterElementReduction.Serialize(writer);
			airElementReduction.Serialize(writer);
			fireElementReduction.Serialize(writer);
			pushDamageReduction.Serialize(writer);
			criticalDamageReduction.Serialize(writer);
			pvpNeutralElementResistPercent.Serialize(writer);
			pvpEarthElementResistPercent.Serialize(writer);
			pvpWaterElementResistPercent.Serialize(writer);
			pvpAirElementResistPercent.Serialize(writer);
			pvpFireElementResistPercent.Serialize(writer);
			pvpNeutralElementReduction.Serialize(writer);
			pvpEarthElementReduction.Serialize(writer);
			pvpWaterElementReduction.Serialize(writer);
			pvpAirElementReduction.Serialize(writer);
			pvpFireElementReduction.Serialize(writer);
			meleeDamageDonePercent.Serialize(writer);
			meleeDamageReceivedPercent.Serialize(writer);
			rangedDamageDonePercent.Serialize(writer);
			rangedDamageReceivedPercent.Serialize(writer);
			weaponDamageDonePercent.Serialize(writer);
			weaponDamageReceivedPercent.Serialize(writer);
			spellDamageDonePercent.Serialize(writer);
			spellDamageReceivedPercent.Serialize(writer);
			writer.writeShort(this.spellModifications.size());
			int _loc2_ = 0;
			while( _loc2_ < this.spellModifications.size()){
				this.spellModifications.get(_loc2_).Serialize(writer);
				_loc2_++;
			}
			writer.writeInt(this.probationTime);
		} catch (Exception e){
			e.printStackTrace();
		}
	}

	@Override
	public void Deserialize(DofusDataReader reader) {
		try {
			this.experience = reader.readVarLong();
			this.experienceLevelFloor = reader.readVarLong();
			this.experienceNextLevelFloor = reader.readVarLong();
			this.experienceBonusLimit = reader.readVarLong();
			this.kamas = reader.readVarLong();
			this.statsPoints = reader.readVarShort();
			this.additionnalPoints = reader.readVarShort();
			this.spellsPoints = reader.readVarShort();
			this.alignmentInfos = new ActorExtendedAlignmentInformations();
			this.alignmentInfos.Deserialize(reader);
			this.lifePoints = reader.readVarInt();
			this.maxLifePoints = reader.readVarInt();
			this.energyPoints = reader.readVarShort();
			this.maxEnergyPoints = reader.readVarShort();
			this.actionPointsCurrent = reader.readVarShort();
			this.movementPointsCurrent = reader.readVarShort();
			this.initiative = new CharacterBaseCharacteristic();
			this.initiative.Deserialize(reader);
			this.prospecting = new CharacterBaseCharacteristic();
			this.prospecting.Deserialize(reader);
			this.actionPoints = new CharacterBaseCharacteristic();
			this.actionPoints.Deserialize(reader);
			this.movementPoints = new CharacterBaseCharacteristic();
			this.movementPoints.Deserialize(reader);
			this.strength = new CharacterBaseCharacteristic();
			this.strength.Deserialize(reader);
			this.vitality = new CharacterBaseCharacteristic();
			this.vitality.Deserialize(reader);
			this.wisdom = new CharacterBaseCharacteristic();
			this.wisdom.Deserialize(reader);
			this.chance = new CharacterBaseCharacteristic();
			this.chance.Deserialize(reader);
			this.agility = new CharacterBaseCharacteristic();
			this.agility.Deserialize(reader);
			this.intelligence = new CharacterBaseCharacteristic();
			this.intelligence.Deserialize(reader);
			this.range = new CharacterBaseCharacteristic();
			this.range.Deserialize(reader);
			this.summonableCreaturesBoost = new CharacterBaseCharacteristic();
			this.summonableCreaturesBoost.Deserialize(reader);
			this.reflect = new CharacterBaseCharacteristic();
			this.reflect.Deserialize(reader);
			this.criticalHit = new CharacterBaseCharacteristic();
			this.criticalHit.Deserialize(reader);
			this.criticalHitWeapon = reader.readVarShort();
			this.criticalMiss = new CharacterBaseCharacteristic();
			this.criticalMiss.Deserialize(reader);
			this.healBonus = new CharacterBaseCharacteristic();
			this.healBonus.Deserialize(reader);
			this.allDamagesBonus = new CharacterBaseCharacteristic();
			this.allDamagesBonus.Deserialize(reader);
			this.weaponDamagesBonusPercent = new CharacterBaseCharacteristic();
			this.weaponDamagesBonusPercent.Deserialize(reader);
			this.damagesBonusPercent = new CharacterBaseCharacteristic();
			this.damagesBonusPercent.Deserialize(reader);
			this.trapBonus = new CharacterBaseCharacteristic();
			this.trapBonus.Deserialize(reader);
			this.trapBonusPercent = new CharacterBaseCharacteristic();
			this.trapBonusPercent.Deserialize(reader);
			this.glyphBonusPercent = new CharacterBaseCharacteristic();
			this.glyphBonusPercent.Deserialize(reader);
			this.runeBonusPercent = new CharacterBaseCharacteristic();
			this.runeBonusPercent.Deserialize(reader);
			this.permanentDamagePercent = new CharacterBaseCharacteristic();
			this.permanentDamagePercent.Deserialize(reader);
			this.tackleBlock = new CharacterBaseCharacteristic();
			this.tackleBlock.Deserialize(reader);
			this.tackleEvade = new CharacterBaseCharacteristic();
			this.tackleEvade.Deserialize(reader);
			this.PAAttack = new CharacterBaseCharacteristic();
			this.PAAttack.Deserialize(reader);
			this.PMAttack = new CharacterBaseCharacteristic();
			this.PMAttack.Deserialize(reader);
			this.pushDamageBonus = new CharacterBaseCharacteristic();
			this.pushDamageBonus.Deserialize(reader);
			this.criticalDamageBonus = new CharacterBaseCharacteristic();
			this.criticalDamageBonus.Deserialize(reader);
			this.neutralDamageBonus = new CharacterBaseCharacteristic();
			this.neutralDamageBonus.Deserialize(reader);
			this.earthDamageBonus = new CharacterBaseCharacteristic();
			this.earthDamageBonus.Deserialize(reader);
			this.waterDamageBonus = new CharacterBaseCharacteristic();
			this.waterDamageBonus.Deserialize(reader);
			this.airDamageBonus = new CharacterBaseCharacteristic();
			this.airDamageBonus.Deserialize(reader);
			this.fireDamageBonus = new CharacterBaseCharacteristic();
			this.fireDamageBonus.Deserialize(reader);
			this.dodgePALostProbability = new CharacterBaseCharacteristic();
			this.dodgePALostProbability.Deserialize(reader);
			this.dodgePMLostProbability = new CharacterBaseCharacteristic();
			this.dodgePMLostProbability.Deserialize(reader);
			this.neutralElementResistPercent = new CharacterBaseCharacteristic();
			this.neutralElementResistPercent.Deserialize(reader);
			this.earthElementResistPercent = new CharacterBaseCharacteristic();
			this.earthElementResistPercent.Deserialize(reader);
			this.waterElementResistPercent = new CharacterBaseCharacteristic();
			this.waterElementResistPercent.Deserialize(reader);
			this.airElementResistPercent = new CharacterBaseCharacteristic();
			this.airElementResistPercent.Deserialize(reader);
			this.fireElementResistPercent = new CharacterBaseCharacteristic();
			this.fireElementResistPercent.Deserialize(reader);
			this.neutralElementReduction = new CharacterBaseCharacteristic();
			this.neutralElementReduction.Deserialize(reader);
			this.earthElementReduction = new CharacterBaseCharacteristic();
			this.earthElementReduction.Deserialize(reader);
			this.waterElementReduction = new CharacterBaseCharacteristic();
			this.waterElementReduction.Deserialize(reader);
			this.airElementReduction = new CharacterBaseCharacteristic();
			this.airElementReduction.Deserialize(reader);
			this.fireElementReduction = new CharacterBaseCharacteristic();
			this.fireElementReduction.Deserialize(reader);
			this.pushDamageReduction = new CharacterBaseCharacteristic();
			this.pushDamageReduction.Deserialize(reader);
			this.criticalDamageReduction = new CharacterBaseCharacteristic();
			this.criticalDamageReduction.Deserialize(reader);
			this.pvpNeutralElementResistPercent = new CharacterBaseCharacteristic();
			this.pvpNeutralElementResistPercent.Deserialize(reader);
			this.pvpEarthElementResistPercent = new CharacterBaseCharacteristic();
			this.pvpEarthElementResistPercent.Deserialize(reader);
			this.pvpWaterElementResistPercent = new CharacterBaseCharacteristic();
			this.pvpWaterElementResistPercent.Deserialize(reader);
			this.pvpAirElementResistPercent = new CharacterBaseCharacteristic();
			this.pvpAirElementResistPercent.Deserialize(reader);
			this.pvpFireElementResistPercent = new CharacterBaseCharacteristic();
			this.pvpFireElementResistPercent.Deserialize(reader);
			this.pvpNeutralElementReduction = new CharacterBaseCharacteristic();
			this.pvpNeutralElementReduction.Deserialize(reader);
			this.pvpEarthElementReduction = new CharacterBaseCharacteristic();
			this.pvpEarthElementReduction.Deserialize(reader);
			this.pvpWaterElementReduction = new CharacterBaseCharacteristic();
			this.pvpWaterElementReduction.Deserialize(reader);
			this.pvpAirElementReduction = new CharacterBaseCharacteristic();
			this.pvpAirElementReduction.Deserialize(reader);
			this.pvpFireElementReduction = new CharacterBaseCharacteristic();
			this.pvpFireElementReduction.Deserialize(reader);
			this.meleeDamageDonePercent = new CharacterBaseCharacteristic();
			this.meleeDamageDonePercent.Deserialize(reader);
			this.meleeDamageReceivedPercent = new CharacterBaseCharacteristic();
			this.meleeDamageReceivedPercent.Deserialize(reader);
			this.rangedDamageDonePercent = new CharacterBaseCharacteristic();
			this.rangedDamageDonePercent.Deserialize(reader);
			this.rangedDamageReceivedPercent = new CharacterBaseCharacteristic();
			this.rangedDamageReceivedPercent.Deserialize(reader);
			this.weaponDamageDonePercent = new CharacterBaseCharacteristic();
			this.weaponDamageDonePercent.Deserialize(reader);
			this.weaponDamageReceivedPercent = new CharacterBaseCharacteristic();
			this.weaponDamageReceivedPercent.Deserialize(reader);
			this.spellDamageDonePercent = new CharacterBaseCharacteristic();
			this.spellDamageDonePercent.Deserialize(reader);
			this.spellDamageReceivedPercent = new CharacterBaseCharacteristic();
			this.spellDamageReceivedPercent.Deserialize(reader);
			int _loc2_  = reader.readShort();
			int _loc3_  = 0;
			this.spellModifications = new ArrayList<CharacterSpellModification>();
			while( _loc3_ <  _loc2_){
				CharacterSpellModification _loc15_ = new CharacterSpellModification();
				_loc15_.Deserialize(reader);
				this.spellModifications.add(_loc15_);
				_loc3_++;
			}
			this.probationTime = reader.readInt();
		} catch (Exception e){
			e.printStackTrace();
		}
	}

	//private void append(){
		//Network.appendDebug("experience : " + this.experience);
		//Network.appendDebug("experienceLevelFloor : " + this.experienceLevelFloor);
		//Network.appendDebug("experienceNextLevelFloor : " + this.experienceNextLevelFloor);
		//Network.appendDebug("experienceBonusLimit : " + this.experienceBonusLimit);
		//Network.appendDebug("kamas : " + this.kamas);
		//Network.appendDebug("statsPoints : " + this.statsPoints);
		//Network.appendDebug("additionnalPoints : " + this.additionnalPoints);
		//Network.appendDebug("spellsPoints : " + this.spellsPoints);
		//Network.appendDebug("alignmentInfos : " + this.alignmentInfos);
		//Network.appendDebug("lifePoints : " + this.lifePoints);
		//Network.appendDebug("maxLifePoints : " + this.maxLifePoints);
		//Network.appendDebug("energyPoints : " + this.energyPoints);
		//Network.appendDebug("maxEnergyPoints : " + this.maxEnergyPoints);
		//Network.appendDebug("actionPointsCurrent : " + this.actionPointsCurrent);
		//Network.appendDebug("movementPointsCurrent : " + this.movementPointsCurrent);
		//Network.appendDebug("initiative : " + this.initiative);
		//Network.appendDebug("prospecting : " + this.prospecting);
		//Network.appendDebug("actionPoints : " + this.actionPoints);
		//Network.appendDebug("movementPoints : " + this.movementPoints);
		//Network.appendDebug("strength : " + this.strength);
		//Network.appendDebug("vitality : " + this.vitality);
		//Network.appendDebug("wisdom : " + this.wisdom);
		//Network.appendDebug("chance : " + this.chance);
		//Network.appendDebug("agility : " + this.agility);
		//Network.appendDebug("intelligence : " + this.intelligence);
		//Network.appendDebug("range : " + this.range);
		//Network.appendDebug("summonableCreaturesBoost : " + this.summonableCreaturesBoost);
		//Network.appendDebug("reflect : " + this.reflect);
		//Network.appendDebug("criticalHit : " + this.criticalHit);
		//Network.appendDebug("criticalHitWeapon : " + this.criticalHitWeapon);
		//Network.appendDebug("criticalMiss : " + this.criticalMiss);
		//Network.appendDebug("healBonus : " + this.healBonus);
		//Network.appendDebug("allDamagesBonus : " + this.allDamagesBonus);
		//Network.appendDebug("weaponDamagesBonusPercent : " + this.weaponDamagesBonusPercent);
		//Network.appendDebug("damagesBonusPercent : " + this.damagesBonusPercent);
		//Network.appendDebug("trapBonus : " + this.trapBonus);
		//Network.appendDebug("trapBonusPercent : " + this.trapBonusPercent);
		//Network.appendDebug("glyphBonusPercent : " + this.glyphBonusPercent);
		//Network.appendDebug("runeBonusPercent : " + this.runeBonusPercent);
		//Network.appendDebug("permanentDamagePercent : " + this.permanentDamagePercent);
		//Network.appendDebug("tackleBlock : " + this.tackleBlock);
		//Network.appendDebug("tackleEvade : " + this.tackleEvade);
		//Network.appendDebug("PAAttack : " + this.PAAttack);
		//Network.appendDebug("PMAttack : " + this.PMAttack);
		//Network.appendDebug("pushDamageBonus : " + this.pushDamageBonus);
		//Network.appendDebug("criticalDamageBonus : " + this.criticalDamageBonus);
		//Network.appendDebug("neutralDamageBonus : " + this.neutralDamageBonus);
		//Network.appendDebug("earthDamageBonus : " + this.earthDamageBonus);
		//Network.appendDebug("waterDamageBonus : " + this.waterDamageBonus);
		//Network.appendDebug("airDamageBonus : " + this.airDamageBonus);
		//Network.appendDebug("fireDamageBonus : " + this.fireDamageBonus);
		//Network.appendDebug("dodgePALostProbability : " + this.dodgePALostProbability);
		//Network.appendDebug("dodgePMLostProbability : " + this.dodgePMLostProbability);
		//Network.appendDebug("neutralElementResistPercent : " + this.neutralElementResistPercent);
		//Network.appendDebug("earthElementResistPercent : " + this.earthElementResistPercent);
		//Network.appendDebug("waterElementResistPercent : " + this.waterElementResistPercent);
		//Network.appendDebug("airElementResistPercent : " + this.airElementResistPercent);
		//Network.appendDebug("fireElementResistPercent : " + this.fireElementResistPercent);
		//Network.appendDebug("neutralElementReduction : " + this.neutralElementReduction);
		//Network.appendDebug("earthElementReduction : " + this.earthElementReduction);
		//Network.appendDebug("waterElementReduction : " + this.waterElementReduction);
		//Network.appendDebug("airElementReduction : " + this.airElementReduction);
		//Network.appendDebug("fireElementReduction : " + this.fireElementReduction);
		//Network.appendDebug("pushDamageReduction : " + this.pushDamageReduction);
		//Network.appendDebug("criticalDamageReduction : " + this.criticalDamageReduction);
		//Network.appendDebug("pvpNeutralElementResistPercent : " + this.pvpNeutralElementResistPercent);
		//Network.appendDebug("pvpEarthElementResistPercent : " + this.pvpEarthElementResistPercent);
		//Network.appendDebug("pvpWaterElementResistPercent : " + this.pvpWaterElementResistPercent);
		//Network.appendDebug("pvpAirElementResistPercent : " + this.pvpAirElementResistPercent);
		//Network.appendDebug("pvpFireElementResistPercent : " + this.pvpFireElementResistPercent);
		//Network.appendDebug("pvpNeutralElementReduction : " + this.pvpNeutralElementReduction);
		//Network.appendDebug("pvpEarthElementReduction : " + this.pvpEarthElementReduction);
		//Network.appendDebug("pvpWaterElementReduction : " + this.pvpWaterElementReduction);
		//Network.appendDebug("pvpAirElementReduction : " + this.pvpAirElementReduction);
		//Network.appendDebug("pvpFireElementReduction : " + this.pvpFireElementReduction);
		//Network.appendDebug("meleeDamageDonePercent : " + this.meleeDamageDonePercent);
		//Network.appendDebug("meleeDamageReceivedPercent : " + this.meleeDamageReceivedPercent);
		//Network.appendDebug("rangedDamageDonePercent : " + this.rangedDamageDonePercent);
		//Network.appendDebug("rangedDamageReceivedPercent : " + this.rangedDamageReceivedPercent);
		//Network.appendDebug("weaponDamageDonePercent : " + this.weaponDamageDonePercent);
		//Network.appendDebug("weaponDamageReceivedPercent : " + this.weaponDamageReceivedPercent);
		//Network.appendDebug("spellDamageDonePercent : " + this.spellDamageDonePercent);
		//Network.appendDebug("spellDamageReceivedPercent : " + this.spellDamageReceivedPercent);
		//for(CharacterSpellModification a : spellModifications) {
			//Network.appendDebug("spellModifications : " + a);
		//}
		//Network.appendDebug("probationTime : " + this.probationTime);
	//}
}
